### ISSUE TITLE
Found Error in Feather Icons  Package.

### ISSUE THREAD

**Issue by tejamaddimsetty** [JideGuru/FlutterFurnitureAppUI#9]
The method 'getIconData' isn't defined for the type 'Feather'.
Try correcting the name to the name of an existing method, or defining a method named 'getIconData'.dartundefined_method.
And I can't solve the error. Could you please assist me in that.
![skdmelkmd](https://user-images.githubusercontent.com/35171449/83067600-8ecabd00-a084-11ea-898c-a98259ddba52.PNG)

**Comment by JideGuru** [comment]
You seem to have updated the packages.
can you make a pr if you get it fixed?

**Comment by JideGuru** [comment]
@tejamaddimsetty i made an update to fix your issue.
You should pull and try again
